version: '3.8'
services:
    server:
        build: ./
        container_name: c_tms_server
        ports:
            - '5000:5000'
        volumes:
            - ./:/app
            - /app/node_modules
