version: '3.8'
services:
    server:
        build: ./
        image: jbsdevden/mern-tms-server
        # container_name: c_tms_server
        # ports:
        #     - '5000:5000'
        volumes:
            - ./:/app
            - /app/node_modules

    # nginx:
    #     image: nginx:latest
    #     volumes:
    #         - ./nginx/conf.d:/etc/nginx/conf.d
    #     depends_on:
    #         - server
    #     ports:
    #         - '5000:5000'
