FROM node:16.16.0-alpine as server-prod-build

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install

COPY ./ ./

EXPOSE 5000

CMD ["yarn", "run", "start"]



FROM nginx:alpine 
COPY /nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 5000