FROM node:16.16.0-alpine as server-prod-build

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install

COPY ./ ./

EXPOSE 5000

# NOTE: Use the run command to build the folder while building the image and not the container
# RUN npm run build
# RUN npm run start


FROM nginx:alpine
COPY /nginx/conf.d /etc/nginx/conf.d/default.conf
# COPY --from=react-prod-build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
