version: '3.8'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - ../nginx/conf.d:/etc/nginx/conf.d
        # depends_on:
        #     - server_1
        ports:
            - 5001:80

    server:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile.prod
        image: 'jbsdevden/mern-tms-server:${GITHUB_SHA}'
        # container_name : server
        restart: always
        volumes:
            - ../:/app
            - /app/node_modules
            - ../nginx/conf.d:/etc/nginx/conf.d
        # ports:
        #     - 5001:5001
        depends_on:
            - nginx
        tty: true
        env_file:
            - ../.env

    # server:
    #     build:
    #         context:  ../
    #         dockerfile: ./docker/Dockerfile.prod
    #     image: 'jbsdevden/mern-tms-server:${GITHUB_SHA}'
    #     volumes:
    #         - ../:/app
    #         - /app/node_modules
    #         - ../nginx/conf.d:/etc/nginx/conf.d
    #     # ports:
    #     #     - 5001:80
    #     expose:
    #         - 5001
    #     env_file:
    #         - ../.env
