FROM node:16.16.0-alpine as server-prod-build

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install

COPY ./ ./

EXPOSE 5000

# NOTE: Use the run command to build the folder while building the image and not the container
# RUN npm run build
# RUN npm run start
CMD ["yarn", "run", "start"]