version: '3.8'
services:
    server:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile.prod
        image: 'jbsdevden/mern-tms-server:${GITHUB_SHA}'
        volumes:
            - ../:/app
            - /app/node_modules
        # ports:
        #     - 5001:5000
        env_file:
            - ../.env

    # nginx:
    #     image: nginx:alpine
    #     volumes:
    #         - ../nginx/conf.d:/etc/nginx/conf.d
    #     depends_on:
    #         - server
    #     expose:
    #         - 8080
    #     ports:
    #         - 5001:8080
