version: '3.8'
services:
    server:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile.prod
        image: 'jbsdevden/mern-tms-server:${GITHUB_SHA}'
        # container_name : server
        restart: unless-stopped
        volumes:
            - ../:/app
            - /app/node_modules
            - ../nginx/conf.d:/etc/nginx/conf.d

        # ports:
        #     - 5001:5001
        # depends_on:
        #     - nginx
        # tty: true
        env_file:
            - ../.env

    nginx:
        image: nginx:alpine
        volumes:
            - ../nginx/conf.d:/etc/nginx/conf.d
        command: nginx -g "daemon off;"
        depends_on:
            - server
        ports:
            - 5001:80

    # server:
    #     build:
    #         context:  ../
    #         dockerfile: ./docker/Dockerfile.prod
    #     image: 'jbsdevden/mern-tms-server:${GITHUB_SHA}'
    #     volumes:
    #         - ../:/app
    #         - /app/node_modules
    #         - ../nginx/conf.d:/etc/nginx/conf.d
    #     # ports:
    #     #     - 5001:80
    #     expose:
    #         - 5001
    #     env_file:
    #         - ../.env
