version: '3.8'
services:
    server:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile.prod
        image: 'jbsdevden/mern-tms-server:${GITHUB_SHA}'
        volumes:
            - ../:/app
            - /app/node_modules
        env_file:
            - ../.env

    # nginx:
    #     image: nginx:alpine
    #     build:
    #         context: ../
    #         dockerfile: ./docker/Dockerfile.prod
    #     volumes:
    #         - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    #     depends_on:
    #         - server
    #     ports:
    #         - 5000:5000
    nginx:
        image: nginx:alpine
        build:
            context: ../
            dockerfile: ./docker/Dockerfile.prod
        volumes:
            - ../nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - server
        ports:
            - 5000:80

    # nginx:
    #     image: nginx:alpine
    #     volumes:
    #         - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    #     depends_on:
    #         - server
    #     ports:
    #         - 5000:5000f
