name: Release

on:
    push:
        branches: ['main']

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - run: docker build -t jbsdevden/mern-tms-server .

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.D_HUB_MERN_TMS_SERVER_AT}}

            - run: docker push jbsdevden/mern-tms-server
