name: Release

on:
    push:
        branches: ['main']

# on:
#     workflow_run:
#         workflows: ['Integration']
#         types:
#             - completed

jobs:
    deploy:
        # if: github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest

        env:
            DH_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
            DH_PASSWORD: ${{secrets.D_HUB_MERN_TMS_SERVER_AT}}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            NODE_ENV: ${{ secrets.NODE_ENV }}
            PRO_CLIENT_URL: ${{ secrets.PRO_CLIENT_URL }}
            PRO_DB_URL: ${{ secrets.PRO_DB_URL }}
            PRO_HOST: ${{ secrets.PRO_HOST }}
            PRO_PORT: ${{ secrets.PRO_PORT }}
            MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
            MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

        steps:
            - uses: actions/checkout@v3

            - name: Generate env file
              run: |
                  touch .env
                  echo JWT_SECRET = ${{ env.JWT_SECRET }} >> .env
                  echo NODE_ENV = ${{ env.NODE_ENV }} >> .env
                  echo PRO_CLIENT_URL = ${{ env.PRO_CLIENT_URL }} >> .env
                  echo PRO_DB_URL = "mongodb+srv://${{secrets.MONGO_USERNAME}}:${{secrets.MONGO_PASSWORD}}@practice.tdza6.mongodb.net/mern-tms?retryWrites=true&w=majority" >> .env
                  echo PRO_HOST = ${{ env.PRO_HOST }} >> .env
                  echo PRO_PORT = ${{ env.PRO_PORT }} >> .env
                  cat .env

            # - run: docker build -t jbsdevden/mern-tms-server .
            - name: Build the images using the compose file
              run: yarn run compose:build:prod

            - name: Set outputs
              id: vars
              run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

            - name: Check outputs
              run: echo ${{ steps.vars.outputs.sha_short }}

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{env.DH_USERNAME}}
                  password: ${{env.DH_PASSWORD}}

            - name: Push the images to docker hub
              #   run: docker push jbsdevden/mern-tms-server
              run: yarn run compose:push
