name: Release

on:
    push:
        branches: ['main']

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - run: docker build -t jbsdevden/mern-tms-server .
            - run: echo "${{secrets.D_HUB_MERN_TMS_SERVER_AT}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
            - run: docker push jbsdevden/mern-tms-server
